ASPTemplateSite/Controllers/ProfileController.cs
using ASPTemplateSite.BLL.UserUtilities;
using ASPTemplateSite.DAL;
using ASPTemplateSite.DAL.Interfaces;
using ASPTemplateSite.DAL.Services;
using ASPTemplateSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPTemplateSite.Controllers
{
    [RESTAuthorize]
    public class ProfileController : Controller
    {
        public ActionResult Account()
        {
            return View(UserManager.Instance.CurrentUser);
        }
        public ActionResult Projects()
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();
            Response.Cookies.Add(new HttpCookie("ASP.NET_SessionId", ""));
            Response.Cookies.Add(new HttpCookie("Token", ""));

            UserManager.Instance.CurrentUser = null;

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Management()
        {
            return View();
        }
    }
}

ASPTemplateSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"></button>
            @Html.ActionLink("Portfolio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse" id="navbarSupportedContent">

                <ul class="nav navbar-nav mr-auto">
                    <li><a href="@Url.Action("Index", "Home")" class="nav-link @(ViewBag.Active == "Home" ? "active" : "")"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="@Url.Action("About", "Home")" class="nav-link @(ViewBag.Active == "About" ? "active" : "")"><i class="fa"></i> About</a></li>
                    <li><a href="@Url.Action("Contact", "Home")" class="nav-link @(ViewBag.Active == "Contact" ? "active" : "")"><i class="fa"></i> Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right ml-auto">
                    <li><a href="#" class="nav-link" data-toggle="modal" data-target="#loginModal"><i class="fa fa-arrow-right"></i> Sign In</a></li>
                </ul>
            </div>
        </div>
    </nav>
    @Html.Partial("Login")
    <div class="container body-content">
        @RenderBody()
        <hr class="my-4">
        <footer>
            <p>&copy; @DateTime.Now.Year - Wojciech Kur ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @if (ViewBag.ShowModal != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                var login = $('#loginModal');
                login.removeClass('fade');
                login.modal();
                login.addClass('fade');

            });
        </script>

        ViewBag.ShowModal = null;
    }
</body>
</html>

ASPTemplateSite/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"></button>
            @Html.ActionLink("Portfolio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse" id="navbarSupportedContent">

                <ul class="nav navbar-nav mr-auto">
                    <li><a href="@Url.Action("Index", "Home")" class="nav-link @(ViewBag.Active == "Home" ? "active" : "")"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="@Url.Action("About", "Home")" class="nav-link @(ViewBag.Active == "About" ? "active" : "")"><i class="fa"></i> About</a></li>
                    <li><a href="@Url.Action("Contact", "Home")" class="nav-link @(ViewBag.Active == "Contact" ? "active" : "")"><i class="fa"></i> Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right ml-auto">
                    <li><a href="@Url.Action("Projects", "Profile")" class="nav-link"> My projects</a></li>
                    <li><a href="@Url.Action("Account", "Profile")" class="nav-link"> Profile</a></li>
                    <li><a href="@Url.Action("Logout", "Profile")" class="nav-link"><i class="fa fa-power-off"></i> Log out</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr class="my-4">
        <footer>
            <p>&copy; @DateTime.Now.Year - Wojciech Kur ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>